const furnitureData = {
    bed: [
      { id: 1, name: "King Size Bed", price: "$300", image: "bed1.jpg", description: "A luxurious king-size bed made from premium wood.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737822404/Bed29_uaekng.jpg" },
      { id: 2, name: "King Size Bed", price: "$300", image: "bed1.jpg", description: "A luxurious king-size bed made from premium wood.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737822405/Bed30_rcnxnk.jpg" },
      { id: 3, name: "King Size Bed", price: "$300", image: "bed1.jpg", description: "A luxurious king-size bed made from premium wood.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737822405/Bed28_jzfcry.jpg" },
      { id: 4, name: "King Size Bed", price: "$300", image: "bed1.jpg", description: "A luxurious king-size bed made from premium wood.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737822403/Bed26_p4fq1e.jpg" },
      { id: 5, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737822403/Bed24_epb1df.jpg" },
      { id: 6, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822403/Bed27_u0byll.jpg" },
  { id: 7, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822403/Bed25_iv2r8i.jpg" },
  { id: 8, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822398/Bed22_dbjz5i.jpg" },
  { id: 9, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822398/Bed23_fdfmjc.jpg" },
  { id: 10, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822397/Bed20_n9lbvt.jpg" },
  { id: 11, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822397/Bed21_a1epib.jpg" },
  { id: 12, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822397/Bed15_aftrut.jpg" },
  { id: 13, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822397/Bed19_sjzkfm.jpg" },
  { id: 14, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822397/Bed16_rwaknw.jpg" },
  { id: 15, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822397/Bed17_k8jkwq.jpg" },
  { id: 16, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822396/Bed14_yrzucd.jpg" },
  { id: 17, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822395/Bed13_mqqo37.jpg" },
  { id: 18, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822388/Bed12_xguqek.jpg" },
  { id: 19, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822387/Bed11_dl43zn.jpg" },
  { id: 20, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822387/Bed9_bcqf93.jpg" },
  { id: 21, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822387/Bed10_usfhdu.jpg" },
  { id: 22, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822386/Bed8_nurtc7.jpg" },
  { id: 23, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822386/Bed7_rks0pl.jpg" },
  { id: 24, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822386/Bed2_hj8rra.jpg" },
  { id: 25, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822386/Bed4_dclppc.jpg" },
  { id: 26, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822386/Bed5_j2iz85.jpg" },
  { id: 27, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822386/Bed6_q4gcsw.jpg" },
  { id: 28, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822385/Bed1_yuhx6g.jpg" },
  { id: 29, name: "Queen Size Bed", price: "$250", image: "bed2.jpg", description: "A stylish queen-size bed with a modern design.", url: "https://res.cloudinary.com/diarqwz4t/image/upload/v1737822385/Bed3_urazyn.jpg" }
  
    ],
    almirah: [
      { id: 1, name: "Modern Almirah", price: "$150", image: "almirah1.jpg", description: "Spacious almirah with a sleek modern look.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825285/Almirah1_nwqwag.jpg" },
      { id: 2, name: "Classic Almirah", price: "$200", image: "almirah2.jpg", description: "Timeless design made with high-quality materials.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825285/Almirah2_ue74fn.jpg" },
      { id: 3, name: "Modern Almirah", price: "$150", image: "almirah1.jpg", description: "Spacious almirah with a sleek modern look.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825286/Almirah4_pxv7pk.jpg" },
      { id: 4, name: "Classic Almirah", price: "$200", image: "almirah2.jpg", description: "Timeless design made with high-quality materials.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825286/Almirah3_r27kx2.jpg" },
      { id: 5, name: "Modern Almirah", price: "$150", image: "almirah1.jpg", description: "Spacious almirah with a sleek modern look.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825285/Almirah5_mtebm3.jpg" },
      { id: 6, name: "Classic Almirah", price: "$200", image: "almirah2.jpg", description: "Timeless design made with high-quality materials.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825286/Almirah7_owyyyl.jpg" },
      { id: 7, name: "Modern Almirah", price: "$150", image: "almirah1.jpg", description: "Spacious almirah with a sleek modern look.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825285/Almirah6_pkeur7.jpg" },
      { id: 8, name: "Classic Almirah", price: "$200", image: "almirah2.jpg", description: "Timeless design made with high-quality materials.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825287/Almirah14_pnupgj.jpg" },
      { id: 9, name: "Modern Almirah", price: "$150", image: "almirah1.jpg", description: "Spacious almirah with a sleek modern look.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825287/Almirah9_f2kb3s.jpg" },
      { id: 10, name: "Classic Almirah", price: "$200", image: "almirah2.jpg", description: "Timeless design made with high-quality materials.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825286/Almirah8_e6xvxp.jpg" },
      { id: 11, name: "Modern Almirah", price: "$150", image: "almirah1.jpg", description: "Spacious almirah with a sleek modern look.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825286/Almirah12_kjdymw.jpg" },
      { id: 12, name: "Classic Almirah", price: "$200", image: "almirah2.jpg", description: "Timeless design made with high-quality materials.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825287/Almirah10_bmhev9.jpg" },
      { id: 13, name: "Modern Almirah", price: "$150", image: "almirah1.jpg", description: "Spacious almirah with a sleek modern look.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825287/Almirah11_oia7h1.jpg" },
      { id: 14, name: "Classic Almirah", price: "$200", image: "almirah2.jpg", description: "Timeless design made with high-quality materials.",url:"https://res.cloudinary.com/diarqwz4t/image/upload/v1737825287/Almirah13_vqa3ko.jpg" },
    ],
    sofa: [
      { id: 1, name: "Leather Sofa", price: "$400", image: "sofa1.jpg", description: "Comfortable leather sofa for a modern living room.",url:"" },
      { id: 2, name: "Fabric Sofa", price: "$350", image: "sofa2.jpg", description: "Elegant fabric sofa in a variety of colors.",url:"" },
    ],
  };
  
  export default furnitureData;